title: Qiang Shen
position: Ph.D. Candidate
affiliation: Jilin University
email: shenqiang_163.com; shenqiang19@mails.jlu.edu.cn
keywords: Ubiquitous Computing; Multimodal Learning; Domain Adaptation; Federated Learning; Meta Learning
google_scholar: https://scholar.google.com/citations?hl=en&user=ye6V22oAAAAJ
github_link: https://github.com/Super-Shen
linkedin: https://www.linkedin.com/in/qiangshen-36b98293/
cv_link: 
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
# domain: super-shen.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url: https://super-shen.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /super-shen.github.io/  
